### PR TITLE
Try fix version not updated in package.json

### PR DESCRIPTION
**Pull request by limtingzhi**
I'm not sure if it is recommended to do this. Else I will revert the last commit.

### CODE REVIEW

**Review by moroine — APPROVED** [review]
No, it's actually recommended I think

**Comment by limtingzhi** [comment]
> No, it's actually recommended I think

@moroine Okay, I will give it a try. Hopefully it works 🙏 .

**Comment by limtingzhi** [comment]
@moroine Oh yeah, it did 😄 . https://github.com/nugit/datetime-utils/commit/0ecbba9e8837af3024e8afdf5f644d6acf6f2f0a.

**Pull request merged**
